development:
  bucket: 'signapp-dev'
  access_key_id: 'AKIAJHMMYZ5GOYGV6OHQ'
  secret_access_key: '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'

test:
  bucket: 'signapp-dev'
  access_key_id: 'AKIAJHMMYZ5GOYGV6OHQ'
  secret_access_key: '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'

production:
  bucket: 'signapp-production'
  access_key_id: 'AKIAJHMMYZ5GOYGV6OHQ'
  secret_access_key: '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'